=== gyangartia216/XML_lab_test/company.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="Company">        
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Employee" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Emp-name" type="xs:string"/>
							<xs:element name="Emp-age" type="xs:integer"/>
							<xs:element name="Emp-salary" type="sal"/>
							<xs:element name="Emp-emailid" type="xs:string"/>
							<xs:element name="Emp-Phonenum" type="xs:integer"/>
							<xs:element name="Emp-designation" type="xs:integer"/>
						</xs:sequence>
                    </xs:complexType>
                </xs:element>
             </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="sal">
    	<xs:restriction base="xs:integer">
    	<xs:minInclusive value="50000"/>
    	<xs:maxExclusive value="200000"/>
    </xs:restriction>
</xs:simpleType>
</xs:schema>

=== gyangartia216/XML_lab_test/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="company.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="company.xsd">
   
   <Employee>
    <Emp-name>Rajat</Emp-name>
    <Emp-age>45</Emp-age>
    <Emp-salary>25000</Emp-salary>
    <Emp-emailid>raju@gmail.com</Emp-emailid>
    <Emp-Phonenum>84723945</Emp-Phonenum>
    <Emp-designation>Tester</Emp-designation>
   </Employee>

   <Employee>
    <Emp-name>Khitish</Emp-name>
    <Emp-age>54</Emp-age>
    <Emp-salary>54000</Emp-salary>
    <Emp-emailid>khitish@gmail.com</Emp-emailid>
    <Emp-Phonenum>45645656</Emp-Phonenum>
    <Emp-designation>Tester</Emp-designation>
   </Employee>

   <Employee>
    <Emp-name>Gyan</Emp-name>
    <Emp-age>24</Emp-age>
    <Emp-salary>70000</Emp-salary>
    <Emp-emailid>gyan@gmail.com</Emp-emailid>
    <Emp-Phonenum>875469435</Emp-Phonenum>
    <Emp-designation>Developer</Emp-designation>
   </Employee>

   <Employee>
    <Emp-name>Yash</Emp-name>
    <Emp-age>37</Emp-age>
    <Emp-salary>50000</Emp-salary>
    <Emp-emailid>sonu@gmail.com</Emp-emailid>
    <Emp-Phonenum>657469435</Emp-Phonenum>
    <Emp-designation>HR</Emp-designation>
   </Employee>

   <Employee>
    <Emp-name>Aman</Emp-name>
    <Emp-age>21</Emp-age>
    <Emp-salary>10000</Emp-salary>
    <Emp-emailid>dixit@gmail.com</Emp-emailid>
    <Emp-Phonenum>43543635</Emp-Phonenum>
    <Emp-designation>Jr Dev</Emp-designation>
   </Employee>

</Company>
